import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import { ReactLenis } from "@/utils/lenis";
import { AppBackgroundGradient } from "@/components/ui/AppBackgroundGradient";
import "./globals.css";

const cabinetGrotesk = localFont({
  src: "./fonts/CabinetGrotesk-Variable.woff2",
  variable: "--font-cabinet-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${cabinetGrotesk.className} antialiased`}>
        <AppBackgroundGradient />
        <ReactLenis
          root
          options={{
            lerp: 0.1,
            duration: 1.2,
            smoothWheel: true,
            touchMultiplier: 2,
          }}
        />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
